name: one_two_three_ddaeng_fe
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  lottie: ^2.4.0
  flutter_svg: ^2.0.6
  flip_card: ^0.7.0
  onboarding: ^3.1.0
  flutter_screenutil: ^5.8.4
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/lottie/
    - assets/svg/
    - assets/png/

  uses-material-design: true
